# Generated by Django 5.2.7 on 2025-10-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footballmatch',
            options={'verbose_name_plural': 'Football Matches'},
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'verbose_name_plural': 'Workout Sessions'},
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight used (kg or lbs)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='workout_type',
            field=models.CharField(help_text='e.g., Strength, Cardio, HIIT', max_length=100),
        ),
    ]
